"""
07 - Create AI Foundry Agent with SQL Function Tool
Creates an AI Foundry agent that converts natural language to SQL and executes queries.

Usage:
    python 07_create_foundry_agent.py

Prerequisites:
    - Run 01_generate_sample_data.py (creates data and ontology_config.json)
    - Run 02_setup_fabric.py (creates Lakehouse and Ontology)
    - Run 03_load_fabric_data.py (loads data to tables)
    - Run 04_generate_prompt.py (creates schema_prompt.txt)

The agent has a function tool 'execute_sql' that must be handled by the test script.
"""

import os
import sys
import json

# Load environment from azd + project .env
from load_env import load_all_env
load_all_env()

from azure.identity import DefaultAzureCredential
from azure.ai.projects import AIProjectClient
from azure.ai.projects.models import PromptAgentDefinition, FunctionTool

# ============================================================================
# Configuration
# ============================================================================

# Azure services - from azd environment
ENDPOINT = os.getenv("AZURE_AI_PROJECT_ENDPOINT")
MODEL = os.getenv("AZURE_CHAT_MODEL") or os.getenv("MODEL_DEPLOYMENT", "gpt-4o")

# Project settings - from .env
DATA_FOLDER = os.getenv("DATA_FOLDER")

if not ENDPOINT:
    print("ERROR: AZURE_AI_PROJECT_ENDPOINT not set")
    print("       Run 'azd up' to deploy Azure resources")
    sys.exit(1)

if not DATA_FOLDER:
    print("ERROR: DATA_FOLDER not set in .env")
    print("       Run 01_generate_sample_data.py first")
    sys.exit(1)

data_dir = os.path.abspath(DATA_FOLDER)

# Set up paths for new folder structure
config_dir = os.path.join(data_dir, "config")
if not os.path.exists(config_dir):
    config_dir = data_dir  # Fallback to old structure

# ============================================================================
# Load Ontology Config and Schema Prompt
# ============================================================================

# Load ontology config for scenario info
config_path = os.path.join(config_dir, "ontology_config.json")
if not os.path.exists(config_path):
    print(f"ERROR: ontology_config.json not found")
    print("       Run 01_generate_sample_data.py first")
    sys.exit(1)

with open(config_path) as f:
    ontology_config = json.load(f)

scenario = ontology_config.get("scenario", "retail")
scenario_name = ontology_config.get("name", "Business Data")
scenario_desc = ontology_config.get("description", "")
tables = list(ontology_config.get("tables", {}).keys())

# Load schema prompt (generated by 04_generate_prompt.py)
prompt_path = os.path.join(config_dir, "schema_prompt.txt")
if os.path.exists(prompt_path):
    with open(prompt_path) as f:
        schema_prompt = f.read()
else:
    schema_prompt = ""
    print("WARNING: schema_prompt.txt not found - run 04_generate_prompt.py first")

# Load Fabric IDs
fabric_ids_path = os.path.join(config_dir, "fabric_ids.json")
if not os.path.exists(fabric_ids_path):
    print(f"ERROR: fabric_ids.json not found")
    print("       Run 02_setup_fabric.py first")
    sys.exit(1)

with open(fabric_ids_path) as f:
    fabric_ids = json.load(f)

WORKSPACE_ID = fabric_ids.get("workspace_id")
LAKEHOUSE_NAME = fabric_ids.get("lakehouse_name")
SOLUTION_NAME = fabric_ids.get("solution_name", "demo")
# Agent names: alphanumeric and hyphens only, must start/end with alphanumeric
AGENT_NAME = f"{SOLUTION_NAME}-nl2sql-agent"

print(f"\n{'='*60}")
print("Creating AI Foundry Agent with SQL Function Tool")
print(f"{'='*60}")
print(f"Endpoint: {ENDPOINT}")
print(f"Model: {MODEL}")
print(f"Scenario: {scenario_name}")
print(f"Tables: {', '.join(tables)}")
print(f"Lakehouse: {LAKEHOUSE_NAME}")

# ============================================================================
# Build Agent Instructions
# ============================================================================

def build_agent_instructions(config, schema_text):
    """Build optimized agent instructions for the scenario"""
    scenario_name = config.get("name", "Business Data")
    scenario_desc = config.get("description", "")
    tables_config = config.get("tables", {})
    relationships = config.get("relationships", [])
    
    # Build table descriptions
    table_names = list(tables_config.keys())
    
    # Build relationship descriptions for JOINs
    join_hints = []
    for rel in relationships:
        from_table = rel.get("from")
        to_table = rel.get("to")
        from_key = rel.get("fromKey")
        to_key = rel.get("toKey")
        join_hints.append(f"{from_table}.{from_key} = {to_table}.{to_key}")
    
    instructions = f"""You are a helpful data analyst assistant that answers questions about {scenario_name} data.

{scenario_desc}

You have access to a SQL execution tool that can run queries against a Fabric Lakehouse.

{schema_text}

## Your Workflow:
1. When a user asks a question, analyze what data they need
2. Generate a valid T-SQL query to answer their question
3. Call the execute_sql function with your query
4. Interpret the results and provide a clear, helpful answer

## SQL Guidelines:
- Use T-SQL syntax compatible with Fabric Lakehouse
- Available tables: {', '.join(table_names)}
- Do NOT use schema prefixes (no dbo.) - just use table names directly
- Use proper aggregation functions: COUNT, SUM, AVG, MIN, MAX
- Always use GROUP BY when using aggregation with non-aggregated columns
- For JOINs use: {'; '.join(join_hints) if join_hints else 'check schema for foreign keys'}
- Use TOP N instead of LIMIT for row limiting

## Response Format:
1. Briefly explain your approach
2. Show the SQL query you'll execute
3. Execute the query
4. Summarize the results clearly with specific numbers

Be concise and accurate. If a query fails, explain the issue and try a different approach."""

    return instructions

instructions = build_agent_instructions(ontology_config, schema_prompt)
print(f"\nBuilt instructions ({len(instructions)} chars)")

# ============================================================================
# SQL Execution Function Tool Definition
# ============================================================================

execute_sql_tool = FunctionTool(
    name="execute_sql",
    description=f"Execute a SQL query against the Fabric Lakehouse and return results. Available tables: {', '.join(tables)}. Use T-SQL syntax.",
    parameters={
        "type": "object",
        "properties": {
            "sql_query": {
                "type": "string",
                "description": f"The T-SQL query to execute. Use table names: {', '.join(tables)}. Do not use schema prefixes."
            }
        },
        "required": ["sql_query"],
        "additionalProperties": False
    },
    strict=True
)

# ============================================================================
# Create the Agent
# ============================================================================

print("\nInitializing AI Project Client...")
credential = DefaultAzureCredential()

try:
    project_client = AIProjectClient(
        endpoint=ENDPOINT,
        credential=credential
    )
    print("[OK] AI Project Client initialized")
except Exception as e:
    print(f"[FAIL] Failed to initialize client: {e}")
    sys.exit(1)

try:
    with project_client:
        # Delete existing agent if it exists
        print(f"\nChecking if agent '{AGENT_NAME}' already exists...")
        try:
            existing_agent = project_client.agents.get(AGENT_NAME)
            if existing_agent:
                print(f"  Found existing agent, deleting...")
                project_client.agents.delete(AGENT_NAME)
                print(f"[OK] Deleted existing agent")
        except Exception:
            print(f"  No existing agent found")

        # Create agent definition with tool
        print("\nCreating agent...")
        agent_definition = PromptAgentDefinition(
            model=MODEL,
            instructions=instructions,
            tools=[execute_sql_tool]
        )
        
        agent = project_client.agents.create(
            name=AGENT_NAME,
            definition=agent_definition
        )
        
        print(f"\n[OK] Agent created successfully!")
        print(f"  Agent ID: {agent.id}")
        print(f"  Agent Name: {agent.name}")
        
except Exception as e:
    print(f"\n[FAIL] Failed to create agent: {e}")
    sys.exit(1)

# ============================================================================
# Save Agent Configuration
# ============================================================================

agent_ids_path = os.path.join(config_dir, "agent_ids.json")
agent_ids = {}
if os.path.exists(agent_ids_path):
    with open(agent_ids_path) as f:
        agent_ids = json.load(f)

agent_ids["foundry_agent_id"] = agent.id
agent_ids["foundry_agent_name"] = agent.name
agent_ids["endpoint"] = ENDPOINT
agent_ids["workspace_id"] = WORKSPACE_ID
agent_ids["lakehouse_name"] = LAKEHOUSE_NAME

with open(agent_ids_path, "w") as f:
    json.dump(agent_ids, f, indent=2)

print(f"\n[OK] Agent config saved to: {agent_ids_path}")

# Update .env with FOUNDRY_AGENT_ID
env_path = os.path.join(script_dir, "..", ".env")
if os.path.exists(env_path):
    with open(env_path, "r") as f:
        env_content = f.read()
    
    lines = env_content.split("\n")
    updated = False
    for i, line in enumerate(lines):
        if line.startswith("FOUNDRY_AGENT_ID="):
            lines[i] = f"FOUNDRY_AGENT_ID={agent.id}"
            updated = True
            break
    
    if updated:
        with open(env_path, "w") as f:
            f.write("\n".join(lines))
        print(f"[OK] Updated .env with FOUNDRY_AGENT_ID={agent.id}")

# ============================================================================
# Summary
# ============================================================================

print(f"""
{'='*60}
AI Foundry Agent Created Successfully!
{'='*60}

Agent ID: {agent.id}
Agent Name: {agent.name}
Model: {MODEL}
Scenario: {scenario_name}

The agent has a function tool 'execute_sql' that you handle in your code.
When the agent calls this function, the test script will:
1. Execute the SQL query against Fabric Lakehouse via pyodbc
2. Return the results to the agent

Next step:
  python scripts/08_test_foundry_agent.py
""")


